

server:
  servlet:
    context-path: /wakimob/api
  port:
    8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wakimob
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create