server:
  servlet:
    context-path: /wakimob/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wakimob
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

api:
  securiry:
    token:
      secret: ${JWT_SECRET:mu-secret-key}

springdoc:
  swagger-ui:
    path: /docs-wakimob.html